version: '3'
services:
  php-environment:
    container_name: hms-php-apache
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html/
    ports:
      - 8080:80
